#!/usr/bin/env bash
#
# Checks code with clippy linter and runs tests
#

set -eu

for profile in dev release; do
    cargo clippy --workspace --all-targets --all-features --no-deps --profile "$profile" -- -Dwarnings
done

cargo test