name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 19 * * 5'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test on ${{ matrix.os }}
    #runs-on: ${{ format('{0}-latest', matrix.os) }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # FIXME(konishchev): Waiting for macos-12 become macos-latest
        # (https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners)
        #os: [ubuntu, macos]
        os: [ubuntu-latest, macos-12]

    steps:
    - uses: actions/checkout@v3

    - name: Drop caches
      run: rm Cargo.lock

    - name: Build
      run: cargo build

    - name: Test
      run: cargo test
